/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.TreeMap;
import java.util.Map;
import java.time.Instant;
import java.time.Duration;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.BufferedWriter;
import java.io.FileWriter;

public class App {
	// Finds the total number of sales for each day
	// Finds all of the sales for each day, sorting them by date, and then by time

	public static void main(String[] args) {
		Instant start = Instant.now();

		// Make sure there is an input file given as an argument
		if (!validateArgs(args)) {
			System.out.println("Two input arguments are needed.");
			return;
		}

		// Open the file and process each of the lines
		processFile(args[0], args[1]);

		Instant end = Instant.now();

		// How long this process took in milliseconds
		Duration elapsed = Duration.between(start, end);
		System.out.println("Time: " + elapsed.toMillis() + "ms");
	}

	private static boolean validateArgs(String[] args) {
		return args.length == 2;
	}

	private static void processFile(String inputPath, String outputPath) {
		// Maps a date to a list of tuples (time and id)
		TreeMap<String, TreeMap<String, Integer>> dayToTimeId = new TreeMap<>();

		// Process the INPUT file
		try (BufferedReader br = new BufferedReader(new FileReader(inputPath))) {
			String line;

			// Process each line in the text file
			while ((line = br.readLine()) != null) {
				processLine(line, dayToTimeId);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

		// Write the results to the OUTPUT file
		try (BufferedWriter bw = new BufferedWriter(new FileWriter(outputPath))) {
			// Show what we got (and some extra stats for me)
			for (Map.Entry<String, TreeMap<String, Integer>> day : dayToTimeId.entrySet()) {
				// Write the day
				bw.write(day.getKey() + "     ");

				// For every time, write the date and then the time
				boolean first = true;
				for (Map.Entry<String, Integer> timeId : day.getValue().entrySet()) {
					if (!first) {
						bw.write(", ");
					}
	
					// Write the time and the id of the sale
					bw.write(timeId.getKey() + " " + timeId.getValue());
					first = false;
				}

				bw.newLine();
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private static void processLine(String line, 
			TreeMap<String, TreeMap<String, Integer>> dayToTimeId) {
		// Parse out the day of the sale
		// This is the second comma delimited string in a line

    String[] tokens = line.split(",");
    if (tokens.length < 3) {
        return;
    }

		String id = tokens[0].trim();
		String date = tokens[1].trim();
		String time = tokens[2].trim();

		if (dayToTimeId.containsKey(date)) {
			// If the key already exists, then thre is already a TreeMap object for the
			// value. do a .put() method for that value
			TreeMap timeToId = dayToTimeId.get(date);
			timeToId.put(time, Integer.parseInt(id));
		}
		else {
			// If the key doesn't exist, then create a new TreeMap<>() object and 
			// assign it with that key
			TreeMap timeToId = new TreeMap<>();
			timeToId.put(time, Integer.parseInt(id));
			dayToTimeId.put(date, timeToId);
		}
	}
}


