/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Files;
import java.nio.file.Path;
import java.io.IOException;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.HashSet;
import java.util.Scanner;

/*
	 Note that the files are stored in app/output directory
*/

public class App {
	public static void main(String[] args) {

		Random rand = new Random();


class VendorCollection {
    private HashSet<Customer> customers;
    private HashSet<Store> stores;
    private HashSet<Product> products;
    private HashSet<Sale> sales;
    private HashSet<LineItem> lineItems;


		try {
			// 1000 iterations
			for (int i = 0; i < 1; i++) {
				Files.writeString(Path.of("output/customer"), 
						String.format("%d, %s, %d/%d/%d, %d %s %s, %s, %d, %s, %d %d %d",
							i,											// ID 
																			// name
																			// birthdate year 
																			// birthdate month 
																			// birthdate month 
																			// address Number
																			// address Name 
																			// city
																			// ZIP
																			// state
																			// phoneNumber
							)
						);
				// "12, John Sam, 1989/11/11, 123 Main St, SLO, 93401, CA, 805 555 5555"
			}
		} catch (IOException e) { 
			e.printStackTrace(); 
		}

		// =========================================================================

		// public static String randomString(int length) {
		// 	return new Random().ints(length, 'a', 'z' + 1)
		// 		.mapToObj(i -> String.valueOf((char) i))
		// 		.collect(Collectors.joining());
		// }


		// 	// 1000 iterations
		// 	for (int i = 0; i < 1; i++) {
		// 		Files.writeString(Path.of("output/customer"), 
		// 				String.format("%d, %s, %d/%d/%d, %d %s %s, %s, %d, %s, %d %d %d",
		// 					i,											// ID 
		// 					// name
		// 					// birthdate year 
		// 					// birthdate month 
		// 					// birthdate month 
		// 					// address Number
		// 					// address Name 
		// 					// city
		// 					// ZIP
		// 					// state
		// 					// phoneNumber
		// 					)
		// 				);
		// 				// "12, John Sam, 1989/11/11, 123 Main St, SLO, 93401, CA, 805 555 5555"
		// 	}

		// 	// 100 iterations
		// 	for (int i = 0; i < 1; i++) {
		// 		Files.writeString(Path.of("output/store"), 
		// 				String.format("%d, %s, %d %s, %s, %d, %s, %d %d %d", 
		// 					i,										// ID 
		// 					// storeName 
		// 					// address Number
		// 					// address Name 
		// 					// city
		// 					// ZIP
		// 					// state
		// 					// phoneNumber
		// 					)
		// 				);
		// 				// "12, Best Buy, 123 Main St, SLO, 93401, CA, 805 555 5555"
		// 	}


		// 	// 2000 iterations
		// 	for (int i = 0; i < 1; i++) {
		// 		Files.writeString(Path.of("output/sales"), 
		// 				String.format("%d, %d/%d/%d, %d:%d:%d, %d, %d",
		// 					i,											// ID 
		// 					// birthdate year 
		// 					// birthdate month 
		// 					// birthdate month 
		// 					// date hour 
		// 					// date minute
		// 					// date second

		// 					// storeID
		// 					// customerID
		// 					)
		// 				);
		// 				// "13, 2017/01/01, 13:23:11, 23, 56"
		// 	}
	
		// 	// 100 iterations
		// 	for (int i = 0; i < 1; i++) {
		// 		Files.writeString(Path.of("output/product"), 
		// 				String.format("%d, %s, %.2f",
		// 					i,											// ID 
		// 					// description
		// 					// price
		// 					)
		// 				);
		// 				// "122, XBox 360, 230.23"
		// 	}

		// 	// 4000 iterations
		// 	for (int i = 0; i < 1; i++) {
		// 		Files.writeString(Path.of("output/lineItem"), 
		// 				String.format("%d, %d, %d, %d", 
		// 					i,											// ID 

		// 					)
		// 				);
		// 				// "11, 13, 122, 8"
		// 	}

	}
}
