/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Files;
import java.nio.file.Path;
import java.io.IOException;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.HashSet;
import java.util.Scanner;

/*
	 Note that the files are stored in app/output directory
	 */

public class App {
	private static HashSet<Customer> customers;
	private static HashSet<Store> stores;
	private static HashSet<Product> products;
	private static HashSet<Sale> sales;
	private static HashSet<LineItem> lineItems;

	public static void main(String[] args) {
		Random rand = new Random();

		/* POPULATE THE HASHSETS */


		/* WRITE FROM THE HASHSETS */
		// For every elemet in a set, write them to a file on a new line
		try {
			// Customers set
			for (Customer c : customers) {
				Files.writeString(Path.of("output/customer"), 
						String.format("%s\n",  c.toString()));
			}

			// Store set
			for (Store c : stores) {
				Files.writeString(Path.of("output/stores"), 
						String.format("%s\n",  c.toString()));
			}

			// Products set
			for (Product c : products) {
				Files.writeString(Path.of("output/products"), 
						String.format("%s\n",  c.toString()));
			}

			// Sales set
			for (Sale c : sales) {
				Files.writeString(Path.of("output/sales"), 
						String.format("%s\n",  c.toString()));
			}

			// LineItems set
			for (LineItem c : lineItems) {
				Files.writeString(Path.of("output/lineItems"), 
						String.format("%s\n",  c.toString()));
			}

		} catch (IOException e) { 
			e.printStackTrace(); 
		}
	}
}
