/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.HashMap;
import java.util.TreeMap;
import java.util.Map;
import java.io.BufferedReader;
import java.io.FileReader;

// TODO: write to a file
// TODO: print the time it takes to finish the main function 

public class App {
	// Finds the total number of sales for each day
	// Does not use Map/Reduce
	public static void main(String[] args) {

		// Make sure there is an input file given as an argument
		if (!validateArgs(args)) {
			System.out.println("One input argument is needed.");
			return;
		}

		// Open the file and process each of the lines
		processFile(args[0]);
	}

	private static boolean validateArgs(String[] args) {
		return args.length == 1;
	}

	private static void processFile(String path) {
		// Maps a date (string) to an int (a sum)
		TreeMap<String, Integer> dayToCt = new TreeMap<>();

		// Open the file at the given directory args[0]
		try (BufferedReader br = new BufferedReader(new FileReader(path))) {
			String line;

			// Process each line in the text file
			while ((line = br.readLine()) != null) {
				processLine(line, dayToCt);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

		// Show what we got (and some extra stats for me)
		System.out.println("Results: ");
		int totalSales = 0;
		for (Map.Entry<String, Integer> day : dayToCt.entrySet()) {
			System.out.println("\t" + day.getKey() + ": " + day.getValue());
			totalSales += day.getValue();
		}

		System.out.println("Total Days: " + dayToCt.size());
		System.out.println("Total Sales: " + totalSales);
	}

	private static void processLine(String line, TreeMap<String, Integer> dayToCt) {
		// Parse out the day of the sale
		// This is the second comma delimited string in a line
    String[] parts = line.split(",");
    if (parts.length < 2) {
        return;
    }

    String day = parts[1].trim();
		dayToCt.put(day, dayToCt.getOrDefault(day, 0)+1);
	}
}

