/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.TreeMap;
import java.util.Map;
import java.time.Instant;
import java.time.Duration;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.BufferedWriter;
import java.io.FileWriter;

public class App {
	// Finds the total number of sales for each day
	// Does not use Map/Reduce
	public static void main(String[] args) {
		Instant start = Instant.now();

		// Make sure there is an input file given as an argument
		if (!validateArgs(args)) {
			System.out.println("Two input arguments are needed.");
			return;
		}

		// Open the file and process each of the lines
		processFile(args[0], args[1]);

		Instant end = Instant.now();

		// How long this process took in milliseconds
		Duration elapsed = Duration.between(start, end);
		System.out.println("Time: " + elapsed.toMillis() + "ms");
	}

	private static boolean validateArgs(String[] args) {
		return args.length == 2;
	}

	private static void processFile(String inputPath, String outputPath) {
		// Maps a date (string) to an int (a sum)
		TreeMap<String, Integer> dayToCt = new TreeMap<>();

		// Process the INPUT file
		try (BufferedReader br = new BufferedReader(new FileReader(inputPath))) {
			String line;

			// Process each line in the text file
			while ((line = br.readLine()) != null) {
				processLine(line, dayToCt);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

		// Write the results to the OUTPUT file
		try (BufferedWriter bw = new BufferedWriter(new FileWriter(outputPath))) {
			// Show what we got (and some extra stats for me)
			for (Map.Entry<String, Integer> day : dayToCt.entrySet()) {
				String outputLine = day.getKey() + ",     " + day.getValue();

				// System.out.println(outputLine);
				bw.write(outputLine);
				bw.newLine();
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private static void processLine(String line, TreeMap<String, Integer> dayToCt) {
		// Parse out the day of the sale
		// This is the second comma delimited string in a line
    String[] parts = line.split(",");
    if (parts.length < 2) {
        return;
    }

    String day = parts[1].trim();
		dayToCt.put(day, dayToCt.getOrDefault(day, 0)+1);
	}
}

