/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Files;
import java.nio.file.StandardOpenOption;
import java.nio.file.Path;
import java.util.HashSet;

/* Note that the files are stored in app/output directory */

public class App {
	private static HashSet<Customer> customers;
	private static HashSet<Store> stores;
	private static HashSet<Product> products;
	private static HashSet<Sale> sales;
	private static HashSet<LineItem> lineItems;

	public static void main(String[] args) {
		/* POPULATE THE HASHSETS */
		// Customers set
		customers = Customer.getFakeCustomers(1000);

		// Store set
		stores = Store.getFakeStores(100);

		// Products set
		products = Product.getFakeProducts(100);

		// Sales set
		sales = Sale.getFakeSales(2000, customers, stores);

		// LineItems set
		lineItems = LineItem.getFakeLineItems(4000, sales, products);

		/* WRITE FROM THE HASHSETS */
		// For every elemet in a set, write them to a file on a new line
		try {
			// Customers set
			System.out.println("Customer set:\n");
			for (Customer c : customers) {
				// System.out.println(String.format("%s\n", c.toString()));
				Files.writeString(
						Path.of("output/customer"),
						String.format("%s\n", c.toString()), 
						StandardOpenOption.CREATE, 
						StandardOpenOption.APPEND);
			}

			// Stores set
			System.out.println("Stores set:\n");
			for (Store s : stores) {
				// System.out.println(String.format("%s\n", s.toString()));
				Files.writeString(
						Path.of("output/stores"),
						String.format("%s\n", s.toString()), 
						StandardOpenOption.CREATE, 
						StandardOpenOption.APPEND);
			}

			// Products set
			System.out.println("Products set:\n");
			for (Product p : products) {
				// System.out.println(String.format("%s\n", p.toString()));
				Files.writeString(
						Path.of("output/products"),
						String.format("%s\n", p.toString()), 
						StandardOpenOption.CREATE, 
						StandardOpenOption.APPEND);
			}

			// Sales set
			System.out.println("Sales set:\n");
			for (Sale s : sales) {
				// System.out.println(String.format("%s\n", s.toString()));
				Files.writeString(
						Path.of("output/sales"),
						String.format("%s\n", s.toString()), 
						StandardOpenOption.CREATE, 
						StandardOpenOption.APPEND);
			}

			// LineItems set
			for (LineItem l : lineItems) {
				// System.out.println(String.format("%s\n", l.toString()));
				Files.writeString(
						Path.of("output/lineItems"),
						String.format("%s\n", l.toString()), 
						StandardOpenOption.CREATE, 
						StandardOpenOption.APPEND);
			}

		} catch (Exception e) { 
			e.printStackTrace(); 
		}
	}
}
